### ISSUE TITLE
CLI command is `mdx` not `mdxc`

### ISSUE THREAD

**Issue by markmur** [frontarm/mdx-util#1]
The readme and your [blog post](http://jamesknelson.com/introducing-mdxc/) states you should use `mdxc <filename>.mdx` to run MDXC but the bin command in the `package.json` is `mdx`.

**Comment by jamesknelson** [comment]
Oh dear, this is why I shouldn't publish things at 1am.

Thanks for pointing this out. Just fixed and published a new npm package which has the binary as `mdxc`.

**Comment by markmur** [comment]
Happy to help 👍
