### ISSUE TITLE
No DNS records for MDXC Playground

### ISSUE THREAD

**Issue by nigelterry** [frontarm/mdx-util#10]
The url mentioned several times in the README http://mdxc.reactarmory.com/ is not resolved by DNS.

**Comment by jamesknelson** [comment]
Thanks for pointing this out, this is due to some recent changes on reactarmory.com

For the moment, you can use http://dump.jamesknelson.com/mdxc-playground.html. I'll leave this open until I fix the new website.

**Comment by jamesknelson** [comment]
Have fixed the website, closing.
