### ISSUE TITLE
option to disable div wrapper (but keep all inside Component)

### ISSUE THREAD

**Issue by 11111000000** [frontarm/mdx-util#12]
```
import { Social } from 'modules/buttons'

<footer className="my-footer"></footer>
```
i.e. I want `<footer></footer>` , not `<div><footer></footer></div>`

**Comment by 11111000000** [comment]
Or to add external wrapper only when top level inner divs more than one? (React restriction)

**Comment by 11111000000** [comment]
any suggestions?

**Comment by jamesknelson** [comment]
You should be able to achieve this by setting the `wrapper` factory. For example, this will make the component render using an array wrapper instead of a div wrapper:

```jsx
<MyMDXComponent factories={{
  wrapper: (props, ...children) => children
}} />
```

You can see how this works by looking at the generated JS:

```jsx
import React, { createElement, createFactory } from 'react'

export default function({ factories={} }) {
  const {
    wrapper = createFactory('div'),
  } = factories

  return wrapper({},

createElement("footer", { className: "my-footer" })

  )
}
```

**Comment by 11111000000** [comment]
thanks! Want this example in documentation! And how to configure that as default behavior in  webpack loader? (all our components have wrapper already)

**Comment by 11111000000** [comment]
And React 16 allow arrays returns...

**Comment by jamesknelson** [comment]
I don't think there is currently a way to configure default factories via the webpack loader (or at all, really).

This is something that has come up before. I'm going to re-open this one, but don't have time to work on it at the moment. If you have a good solution, I'd be happy to merge it.

**Comment by simonlc** [comment]
I was getting an error about keys so I changed this:

```jsx
<MyMDXComponent factories={{
  wrapper: (props, ...children) => children
}} />
```

To this:

```jsx
<MyMDXComponent factories={{
  wrapper: (props, ...children) => React.Children.toArray(children),
}} />
```

**Comment by jamesknelson** [comment]
Closing this issue as I've deprecated mdxc in favor of https://github.com/mdx-js/mdx
