### ISSUE TITLE
Access to props list

### ISSUE THREAD

**Issue by 11111000000** [frontarm/mdx-util#13]
i.e. 
```
prop children

<div {...props} > { children } </div>
```

**Comment by jamesknelson** [comment]
By "access to props list", do you mean access to *all* the passed in props, as opposed to access to individual props?

**Comment by 11111000000** [comment]
I want the whole `{...props}`

**Comment by jamesknelson** [comment]
The problem with providing access to all props is the `factories` prop is in there, but it would make sense to have access to everything else.

How about changing the format so instead of specifying each prop on a separate line, probs are specified as a single line, using ES6 destructuring syntax?

```
// Access individual props
props { prop1, prop2, ...other }

// If you specify how to destructure, everything is accessible under `props`
props
```

**Comment by 11111000000** [comment]
:+1:

**Comment by jamesknelson** [comment]
Closing this issue as I've deprecated mdxc in favor of https://github.com/mdx-js/mdx
