### ISSUE TITLE
way to use Markdown-it plugins

### ISSUE THREAD

**Issue by 11111000000** [frontarm/mdx-util#14]
How to add and enable markdown-it plugins (and in webpack-loader)

**Comment by jamesknelson** [comment]
You use markdown-it plugins the same way as you do with markdown-it, just call `use`.

I don't really want to add this to the documentation, as not all markdown-it plugins are supported. But for plugins that *are* supported, you can see an example in the source for mdx-loader:

https://github.com/jamesknelson/mdx-loader/blob/master/index.js
