### ISSUE TITLE
spaces before markdown tag

### ISSUE THREAD

**Issue by 11111000000** [frontarm/mdx-util#15]
```
   <markdown>
- some
- markdown
- here
   </markdown>
```
renders as a plain text
(without spaces before <markdown> - works as as expected)

**Comment by jamesknelson** [comment]
Yep, this is a known issue. Pull requests would be welcome, but I don't think it would be an easy fix.

**Comment by jamesknelson** [comment]
Closing this issue as I've deprecated mdxc in favor of https://github.com/mdx-js/mdx
