### ISSUE TITLE
getFactoryTag custom fallback

### ISSUE THREAD

**Issue by plexigras** [frontarm/mdx-util#17]
I would like to be able to easily change the fallback from `createFactory('${tag}')` to something else like `(props, children) => h('${tag}', props, ...children)`.

https://github.com/jamesknelson/mdxc/blob/3f05f56c3e8ddc0a32b72bfa65d6f28e0ee6535b/source/mdxc.js#L91-L93

**Comment by jamesknelson** [comment]
@plexigras Makes sense. What would make it easier in your environment?

If you're using the raw `MDXC` class, you should just be able to subclass MDXC and override that method.

**Comment by plexigras** [comment]
Im using the webpack loader and for now i have just set a different import for `createFactory`.

**Comment by jamesknelson** [comment]
I like this solution. I'll leave this open until I've added it to docs.

**Comment by jamesknelson** [comment]
Closing this issue as I've deprecated mdxc in favor of https://github.com/mdx-js/mdx
