### ISSUE TITLE
Rendering mdxc generated JS as component

### ISSUE THREAD

**Issue by tb** [frontarm/mdx-util#26]
How can I render mdxc generated JS as component, like:

    import React from 'react';
    import MDXC from 'mdxc';
    
    var mdxc = new MDXC({
      linkify: true,
      typographer: true,
    });
    
    const js = mdxc.render('# This is a heading');
    
    export default () => js;

The code above renders js source.

PS This is just example, the use case is to load dynamically all posts for a blog or markdown content loaded via API.

**Comment by tb** [comment]
I got this working with following code:

    import React, { Component } from 'react';
    import MDXC from 'mdxc';
    import ReactDOMServer from 'react-dom/server';

    const mdxc = new MDXC({
      commonJS: true,
      pragma: 'createElement',
      linkify: true,
      typographer: true
    })

    const Button = ({children, ...rest}) =>
      <button {...rest}>{children} Button</button>

    const src = mdxc.render(`prop label
    prop type
    
    # Markdown title
    
    <Button className={type}>{label}</Button>
    
    `);

    const render = (code, props) => {
      const module = { exports: null };
      const { createFactory, createElement } = React;
      eval(code); /* eslint no-eval: 0 */
      return module.exports.bind({
        createFactory,
        createElement,
        ...props.factories,
      })(props);
    }

    class App extends Component {
      render() {
        const props = {
          factories: { Button },
          label: 'Dynamic Prop',
          type: 'primary',
        }

        const rendered = render(src, props)

        return (
          <div className="App">
            <h2>src:</h2>
            <pre>{src}</pre>
            <h2>html:</h2>
            <pre>{ReactDOMServer.renderToString(rendered)}</pre>
            <h2>rendered:</h2>
            {rendered}
          </div>
        );
      }
    }

    export default App;

Create-react-app output is:

<img width="836" alt="screen shot 2018-03-04 at 13 15 21" src="https://user-images.githubusercontent.com/71683/36945422-291dd112-1fae-11e8-8aae-4ebe5edf7c43.png">

**Comment by jamesknelson** [comment]
@tb Bit of a late reply, but I just want to mention that while this is possible, you probably shouldn't do this on a public website, as it can be a big security hazard - it will allow users to run any scripts they want.

**Comment by tb** [comment]
@jamesknelson How it this different from loading via webpack loader? You evaluate the markdown there and produce javascript that is loaded into page too.

**Comment by jamesknelson** [comment]
The assumption with a webpack loader is that you're processing your own files, so they're safe. However, if you pass files from untrusted users through the webpack loader, you'll run into the same issue (and worse).
