### ISSUE TITLE
Want PR / help? React 16 support

### ISSUE THREAD

**Issue by DTrejo** [frontarm/mdx-util#27]
Just curious, how difficult do you think it'd be to upgrade it as a person new to the project? 

I want to see if I can use it with the latest next.js

Thanks,  
D

**Comment by manovotny** [comment]
@DTrejo I am using MDXC just fine with the latest version stable version of Next.js (5.1.0) and React 16.3.2 using the [next-mdxc](https://github.com/zeit/next-plugins/tree/92755f02619cb645756b1d46ec9ddd1216142821/packages/next-mdxc) plugin. There shouldn't be any issues with using MDXC with Next.js.

**Comment by jamesknelson** [comment]
@manovotny Thanks for confirming it is working - will close this issue for now.
