### ISSUE TITLE
Code blocks without a language render as inline code

### ISSUE THREAD

**Issue by manovotny** [frontarm/mdx-util#29]
If you use code blocks with a language, like so...

````
```javascript
var i = 0;
```
````

...then it will render the code block, as expected, using `<pre>`.

However, if you use code blocks without a language, like so...

````
```
var i = 0;
```
````

...then it will render the code block as inline code using `<code>`.

It appears to be an issue with MDXC and not markdown-it if you use them on their live demo sites.

![mdxc-vs-markdown-it-code-blocks](https://user-images.githubusercontent.com/446260/38969391-b8f4b13c-4355-11e8-93f0-44559b56a0d4.gif)

**Comment by manovotny** [comment]
I've tried to dig into this off and on over the past day, but I've come up empty handed. In case it helps narrow down the problem, here's what I've tried.

I was able to add a failing test, but adding the following to `test/fixtures/unwrapped/code.txt`

````
.
```
{test}
```
.
codeBlock({}, "{test}\n")
.
````

Which did produce the following failure.

<img width="873" alt="code txt mdxc 2018-04-18 22-20-20" src="https://user-images.githubusercontent.com/446260/38969601-b3da918e-4356-11e8-93fe-e8372bb9fc85.png">

From there, I placed a truckload of `console.log` statements trying to pinpoint the issue.

Everything looks good until you get into the `render` function of `mdxc.js`. Specifically, [the call to `this.parse`](https://github.com/jamesknelson/mdxc/blob/6d72fa235f21c77aaf71818133d46c0d6ca7d924/packages/mdxc/src/mdxc.js#L145).

The call to `this.parse` will call the [`parse` function in `mdxc.js`](https://github.com/jamesknelson/mdxc/blob/6d72fa235f21c77aaf71818133d46c0d6ca7d924/packages/mdxc/src/mdxc.js#L99-L131) and everything still looks good there until it [makes the call to `super.parse`](https://github.com/jamesknelson/mdxc/blob/6d72fa235f21c77aaf71818133d46c0d6ca7d924/packages/mdxc/src/mdxc.js#L130), which calls the `parse` function down in the `MarkdownIt` class.

That call to `super.parse` will return the following.

```
[ Token {
    type: 'fence',
    tag: 'code',
    attrs: null,
    map: [ 0, 3 ],
    nesting: 0,
    level: 0,
    children: null,
    content: '{test}\n',
    markup: '```',
    info: '',
    meta: null,
    block: true,
    hidden: false } ]
```

It's at that point it's already made up it's mind that it should be a `code` and not a `codeBlock`.

And that's where I am stuck.

I know the online demos point the finger to MDXC, but the fact that the `super.parse` call is what returns the `code` tag leads me to believe it's a markdown-it issue somewhere. 

Maybe [the factories and ruler overrides / replacements in MDXC](https://github.com/jamesknelson/mdxc/blob/6d72fa235f21c77aaf71818133d46c0d6ca7d924/packages/mdxc/src/mdxc.js#L17-L32) make markdown-it call back to MDXC to cause the problem, but I sure can't seem to find it.

I'd be happy to dig in further if someone could point me in the right direction, but at this point, I am stumped. :disappointed:

**Comment by jamesknelson** [comment]
Thanks for the detailed issue! Should come in pretty handy when I get around to trying to solve it - probably will be a few weeks though due to work :-(

**Comment by jamesknelson** [comment]
Closing this issue as I've deprecated mdxc in favor of https://github.com/mdx-js/mdx
