### ISSUE TITLE
CRLF breaks importing components when used with front matter

### ISSUE THREAD

**Issue by j1mie** [frontarm/mdx-util#30]
Hi there, great project!

When I try to import a component below front matter like so:

```
---
title: Example
description: This is an example
---
import { MDXBreadboard } from 'mdx-breadboard'
```

It sometimes throws an error: 

`Uncaught ReferenceError: MDXBreadboard is not defined`

When I remove the front matter, the component seems to work just fine.

Any suggestions?

**Comment by jamesknelson** [comment]
Do you need to import the `MDXBreadboard` package? If not, just remove that last line - the demo uses it, but you probably don't need it in your own site.

If that doesn't solve the problem, feel free to reopen this.

**Comment by j1mie** [comment]
Hi @jamesknelson this issue isn't relating to `MDXBreadboard` but any component that's imported this way, below front matter. Are you able to replicate this issue?

**Comment by jamesknelson** [comment]
Is the error appearing during compilation, or once you run the result? Are you using the loader?

Does the error appear when you paste your content into http://mdxc.reactarmory.com/?

**Comment by j1mie** [comment]
Seems to work fine with your example, I'm using an ejected CRA - so could be a dependency issue. I'll test and get back to you!

**Comment by j1mie** [comment]
Hey there @jamesknelson - tried this again on a fresh CRA instance and getting the same effect.

**Error (missing component):**
<img width="480" alt="screen shot 2018-05-03 at 11 32 20" src="https://user-images.githubusercontent.com/12685163/39572124-e8d307de-4ec5-11e8-93c7-d8c2ef4a8cb0.png">

**Seems to be putting import statement within `<p>` tags**
<img width="292" alt="screen shot 2018-05-03 at 11 32 34" src="https://user-images.githubusercontent.com/12685163/39572125-e8ec81be-4ec5-11e8-8f87-75b0e994dd46.png">

**The markdown**
<img width="296" alt="screen shot 2018-05-03 at 11 33 15" src="https://user-images.githubusercontent.com/12685163/39572126-e90541ae-4ec5-11e8-913b-e2634e833c74.png">

I'm following the [Create React App instructions](https://github.com/jamesknelson/mdxc#create-react-app) and rendering out a `<DocumentComponent />` in my App.js:

```js
/* eslint-disable import/no-webpack-loader-syntax */
import DocumentComponent from '!babel-loader!mdx-loader!../pages/index.md'

...

render() {
  <DocumentComponent />
}

```
It's worth noting that this issue only seems to happen intermittently, on some markdown files. I've yet to figure out why.

**Comment by jamesknelson** [comment]
The `p({}, "import`... is interesting - for some reason, the import statement is being treated as raw text.

Any chance you could make a pastebin of one of the source files with the issue?

**Comment by j1mie** [comment]
I've figured this out. It doesn't work for files using `CRLF` line separators.

**Comment by j1mie** [comment]
Don't think I've permission to re-open @jamesknelson

**Comment by jamesknelson** [comment]
Thanks for figuring that out. If you can do a PR I'd be happy to merge it, otherwise I'll try and put a fix together once I have some time.

**Comment by jamesknelson** [comment]
Closing this issue as I've deprecated mdxc in favor of https://github.com/mdx-js/mdx
