### ISSUE TITLE
parcel-plugin

### ISSUE THREAD

**Issue by jthegedus** [frontarm/mdx-util#38]
Using the `@mdx-js/parcel-plugin-mdx` parcel plugin I was able to get close to what you provide with `mdx-loader` for webpack, but was unable to get front-matter working as you have here.

```javascript
// mdx.config.js
const images = require("remark-images");
const slug = require("remark-slug");
const mdxTableOfContents = require("mdx-table-of-contents");
const rehypePrism = require("mdx-loader/rehype-prism");

module.exports = {
  mdPlugins: [images, slug],
  hastPlugins: [rehypePrism],
  compilers: [mdxTableOfContents],
};
```

The problem (as far as I can tell) being that your front-matter solution uses the src markdown but at the compiler step, which I believe is not available at that time.

I tried using `remark-frontmatter`, like so

```javascript
// mdx.config.js
const images = require("remark-images");
const slug = require("remark-slug");
const frontmatter = require("remark-frontmatter");
const mdxTableOfContents = require("mdx-table-of-contents");
const rehypePrism = require("mdx-loader/rehype-prism");

module.exports = {
  mdPlugins: [[frontmatter, { type: "yaml", marker: "-" }], images, slug],
  hastPlugins: [rehypePrism],
  compilers: [mdxTableOfContents],
};
```

but the frontmatter info doesn't make it through the rest of the mdx process.

Any ideas how to support your frontmatter solution in Parcel

**Comment by jamesknelson** [comment]
I'm not sure sorry, I haven't used Parcel yet. Try asking at @mdx-js/parcel-plugin-mdx.
