### ISSUE TITLE
Prism plugins

### ISSUE THREAD

**Issue by jthegedus** [frontarm/mdx-util#39]
I cannot see how I can use your `rehype-prism` solution to pass in a prism config. Is this supported at this time?

**Comment by jamesknelson** [comment]
It's not currently supported, but it may be possible to add an option to mdx-loader that allows prism configuration to be passed in! Would you like to do this as a PR?

**Comment by jamesknelson** [comment]
I've just switched mdx-loader to use Prism (it was previously using the "refractor" package). This should make it easier to pass in prism-specific config.

What kind of config in particular do you want to pass in? Do you have an example of another project that allows you to pass config to prism?

**Comment by jthegedus** [comment]
I do not. Particularly I just wanted to use [prism plugins](https://prismjs.com/#plugins)

**Comment by jamesknelson** [comment]
I've taken a look, but am not really sure how to approach this as the ones I've seen appear to assume that prism is loaded as a `<script>` tag.

Closing this for the moment, but happy to re-open it if you can provide more details on a possible solution.
