### ISSUE TITLE
SyntaxError: Expected corresponding JSX closing tag

### ISSUE THREAD

**Issue by helfi92** [frontarm/mdx-util#43]
I have a markdown file with the following content:

```
3. For running tests within a test file, add "--grep <phrase>" when running
   the above command to capture just the individual test name.
```

When I try to use mdx-loader, I get an error in the terminal `Expected corresponding JSX closing tag for <phrase>`.

Do you know of any way I could have this fixed without changing the markdown file directly (i.e., without wrapping it with backticks). fwiw, none of my markdown files have jsx in them and so I was wondering if there's some kind of option I could disable so that `<phrase>` is treated as plain text but something like `<div>test</div>` is treated like html. Thanks!

**Comment by jamesknelson** [comment]
Unfortunately this is how @mdx-js/mdx (the underlying library) is designed. As far as I know, there's no way to solve this without replacing `<` with `&lt;` and `>` with `&gt;`

**Comment by helfi92** [comment]
Sounds good, thanks!
