### ISSUE TITLE
Need to upgrade to v1 of "@mdx-js/mdx" to render JSX mid-line

### ISSUE THREAD

**Issue by adueck** [frontarm/mdx-util#47]
Currently JSX does not work in the middle of components with `mdx-loader`, because it is using an old version of `@mdx-js/mdx`.

This works

```
<span style={{ color: "red }}>I'm red</span>
```

But this doesn't, it breaks the build 😢 

```
I'm a paragraph in markdown <span style={{ color: "red" ]}>And I'm red</span>
```

This [should be supported with mdx version 1](https://github.com/mdx-js/mdx/issues/543)

Upgrading to v1 of `@mdx-js/mdx` will fix this.

**Comment by adueck** [comment]
Unfortunately this update does not solve this issue for some reason. This is strange because this should be supported with the latest version of `mdx`

Instead I keep getting these error messages:

```
Expected corresponding JSX closing tag for <MDXTag>

> 55 | <MDXTag name="p" components={components}>{`I’m a paragraph in markdown <span style={{ color: “red” ]}>And I’m red`}</span></MDXTag>
     |                                                                                                                    ^
```

**Comment by adueck** [comment]
Ouch... but then this breaks something else. 😞  The files all load fine, front matter and everything comes through with the updated updated `@mdx-js/mdx` but then when you try to render the component from the import in React this happens:

Using my experimental [updated forked version of mdx-loader](https://github.com/adueck/updated-mdx-loader):

```
import React from 'react';
/* eslint-disable import/no-webpack-loader-syntax */
import About from '!babel-loader!updated-mdx-loader!./content/intro/about.mdx';

function App() {
    return (
        <About />
    )
}
```

Error Message:

```
ReferenceError: mdx is not defined
MDXContent
http://localhost:3000/static/js/main.chunk.js:1260:3

...

> 1260 | return mdx(MDXLayout, Object.assign({}, layoutProps, props, {
       | ^  1261 |   components: components,
  1262 |   mdxType: "MDXLayout",
  1263 |   __source: { 
```

**Comment by jamesknelson** [comment]
I haven't been keeping up with API changes lately, but looking at the error, it looks like you'll need to change the existing imports from:

```js
import { MDXTag } from '@mdx-js/tag'
```

https://github.com/adueck/updated-mdx-loader/blob/master/index.js#L48

to something that imports an `mdx` function.

If you can get this working I'm more than happy to merge it!

**Comment by adueck** [comment]
@jamesknelson Hmm, looking back the error message I gave may have been misleading:

I clicked the 'view compiled' button below the red error message from webpack, and got that. The actual error message as it first comes was:

<img width="757" alt="Screenshot 2019-05-30 10 46 43" src="https://user-images.githubusercontent.com/12955501/58617286-67ea7700-82c8-11e9-9d41-ee021bf49126.png">

This might be over my level to get this working...

It would be really, really wonderful if this package could be updated to work with the new stable mdx (and mid-markdown JSX), because [as you explained so well here](https://frontarm.com/james-k-nelson/mdx-with-create-react-app/) there's nothing quite like this out there! 🙇 

Thanks for your super helpful work!

**Comment by adueck** [comment]
The issue seems to be that with v1 of `@mdx-js/mdx` `await mdx(mdxContent, options)` returns a quite different `result`

given a markdown file of:

```
This is a markdown paragraph
```

using @mdx-js/mdx v 0.16.0 `result` is: **(This renders fine)**

```
const layoutProps = {
  
};
export default class MDXContent extends React.Component {
  constructor(props) {
    super(props)
    this.layout = null
  }
  render() {
    const { components, ...props } = this.props

    return <MDXTag
             name="wrapper"
             
             components={components}><MDXTag name="p" components={components}>{`I’m a markdown paragraph`}</MDXTag>
           </MDXTag>
  }
}
```

And using the new @mdx-js/mdx v. 1.0.20 `result` is: **(this breaks things)**

```
/* @jsx mdx */


const makeShortcode = name => function MDXDefaultShortcode(props) {
  console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope")
  return <div {...props}/>
};

const layoutProps = {
  
};
const MDXLayout = "wrapper"
export default function MDXContent({
  components,
  ...props
}) {
  return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">
    <p>{`I’m a markdown paragraph`}</p>
    </MDXLayout>;
}
```

<img width="410" alt="Screenshot 2019-05-30 12 08 13" src="https://user-images.githubusercontent.com/12955501/58622230-cff28a80-82d3-11e9-863d-f4f49915237c.png">


So how to adjust things so that this new `result` can get rendered properly? I'm stuck. 🤔

**Comment by adueck** [comment]
Something to do with using https://www.npmjs.com/package/@mdx-js/react ? 🤔

**Comment by adueck** [comment]
Ok I figured it out! 😄

With the new `result` that comes from `@mdx-js/mdx` v. 1, you need to include the following:

```
import { mdx } from '@mdx-js/react'
```

Now with [my updated PR](https://github.com/frontarm/mdx-util/pull/49) it works great. 👍
