### ISSUE TITLE
Best way to create custom output

### ISSUE THREAD

**Issue by tauren** [frontarm/mdx-util#5]
I'm creating a live documentation and demo site, so I'd like to render markup within a code highlighter, but also show it live on the page. I could write markdown like this:

```markdown
prop buttonType
import Button from 'Button'

# Button

<Button className={buttonType}>Button with {buttonType} styling</Button>

​```jsx
<Button className={buttonType}>Button with {buttonType} styling</Button>
​```
```

However, I'd like to avoid repeating the markup in the markdown document. What I'd like is to write markdown like this:

```markdown
prop buttonType
import Button from 'Button'

# Button

​```example
<Button className={buttonType}>Button with {buttonType} styling</Button>
​```
```

And have it render something like:

```html
<div class="example">
  <div class="live">
    <Button class="primary">Button with primary styling</Button>
  </div>
  <div class="code">
    <pre><code>
      <Button className={buttonType}>Button with {buttonType} styling</Button>
    </code></pre>
  </div>
</div>
```

I can think of several possible ways to do this, but I'm hoping to get some feedback on what might be preferred. 

1. Write a custom webpack loader that processes the markdown looking for the `example` code fences and converts it into html before the `mdx-loader` is run. 
2. Write a `markdown-it` plugin. 
3. Use the `markdown-it-container` plugin, such as `::: example`
4. Write a custom factory that could handle something like `<example> ... </example>`?
5. Something else?

I'm leaning toward option 1 since I'm experienced writing webpack loaders and am not experienced with `markdown-it`, how to write plugins for it, or how to use `markdown-it-container`. Option 1 would allow me to transform the markdown before MDXC even sees it.

However, I wouldn't mind giving the `markdown-it` approaches a try, I'm just not sure which direction makes the most sense, or if there are other options I should consider. I played with `markdown-it-container` some, but was not getting the results I was hoping. I had hoped to transform the `::: example` into to HTML markup in a "first pass", and then let MDXC/markdown-it process everything after my transform. But my HTML was getting output as raw text strings.

Note that for simplicity, in the examples above, I'm using a very basic React `Button` component and a rather non-sensical `buttonType` prop. In reality, this is to demo and document a library of custom Web Components as well as custom React components. Both the Web Components and React Components have much more complex interfaces, accepting multiple attributes/properties, child markup, slots, etc.

**Comment by jamesknelson** [comment]
This is the same use case I originally put MDXC together for. I've actually got a private repo which does the same sort of thing.

The approach I take is completely different, though.

- I remove highlighting by setting the `highlight` option to `false` via mdx-loader
- Then provide a custom `codeBlock` factory that receives the source for each code block as children, and parses out the `language` and some options from the `className` prop

```js
function getBlockOptions(str) {
  const optionStrings = str.replace(/^\{|\s|\}$/g, '').split(',')
  const options = {}
  for (let str of optionStrings) {
    if (str.indexOf('=') === -1) {
      options[str] = true
    }
    else {
      const parts = str.split('=')
      options[parts[0]] = parts[1]
    }
  }
  return options
}

renderCodeBlock = (props, children) => {
    const source = children || props.children
    const language = props.className.replace(/^language-/, '')
}
if (language.slice(0, 3) === 'jsx') {
      const options = getBlockOptions(language.slice(4))
      // ...
}
```

- Use PrismJS or Codemirror to create a highlighted (and possibly editable) version of the source at runtime
- Use Babel to compile the source at runtime, then `eval` it to render it.

A PrismJS component shouldn't be too hard. I've put up a [gist](https://gist.github.com/jamesknelson/b6cb32764ca4e769b38d708df987f049) with my component. A Codemirror component is a little more involved -- I can try and clean up my component and share it if you want it.

Compiling and evaling the code was been painful. I've put together a component called [armo-breadboard](https://github.com/jamesknelson/armo-breadboard) to do this, but it still is lacking in documentation.

Lastly, this is all pretty heavy. My current task is to find a way to split out babel/prism/codemirror into a separate bundle but still have everything rendered statically up front, otherwise mobile users will be waiting a looong time before they see anything.

**Comment by tauren** [comment]
Wow, this is great information! It's clear you've put a ton of effort into this. For me, the documentation site is one small aspect of a much larger project (building the actual components and a full application that uses them), and it's becoming a huge time sink. I already tried several other approaches (and ran into roadblocks with each of them) before discovering MDXC. Thank you for all the time you've devoted to solving this problem!

At this point, I need a quick solution just to display a live component next to the code that rendered it. It doesn't need to be editable for now, but that would be a great enhancement down the road. 

I wrote this basic webpack loader that converts ` ```jsx example` code blocks into custom markup before running it through `mdx-loader`:

```js
module.exports = function exampleLoader(source) {
  return source.replace(/^```(.*)[\s]+example[\s]([\S|\s]*?)^```[\s]*$/mg,
'\n\
<div className="example">\n\
<div className="live">\n\
$2\
</div>\n\
<div className="code">\n\
<markdown>\n\
\n\
```$1\n\
$2\
```\n\
\n\
</markdown>\n\
</div>\n\
</div>\n\
\n')
}
```

That code is messy mostly because I'm not using template literals to avoid having to transpile the loader. But I've also found that line breaks are important or things don't work correctly. For instance, the `<markdown>` tag must be at the start of a line. You can see the regex in action here:
https://regex101.com/r/3mHPLX/3

This solves my immediate need (assuming you publish my PRs), but I still don't think it is ideal. I'll dig into what you've posted above when I have a little free time, as I'm sure your approach is better. Also, if you end up releasing a library that wraps all of this up into an easy to accomplish solution, I'd be delighted to be an alpha-tester!

One last note in case you are interested... I'm creating custom web components using `skatejs`. To get them working within a react app, I'm using `@skatejs/val` to wrap `React.createElement`<sup>1</sup>. The wrapped version is then imported into jsx files as `import h from '../utils/wrap'`. This is why I need `pragma` support.

---

<sup>1</sup>From the `@skatejs/val` website: "The problem with React is that you can't pass complex data structures to DOM elements that have properties that aren't in their whitelist, which every web component would be subject to." The `@skatejs/val` library solves this as well as exposing events emitted from web components to the react app.

**Comment by jamesknelson** [comment]
Ok, I'll close this for the moment. I'm not sure if I'll have time to release a library that ties it all together, but if you do decide to dig into breadboard shoot me an e-mail or leave an issue with any questions!
