### ISSUE TITLE
Mdx macro breaking with latest cra version 3.1.1

### ISSUE THREAD

**Issue by borisrorsvort** [frontarm/mdx-util#54]
![image](https://user-images.githubusercontent.com/39081/63007174-6de00500-be80-11e9-95d8-ce4a21354226.png)
Mostly complaining about babel-preset-react-app being 4 major versions outdated.
Could this be updated or is there a better way to load mdx now?

**Comment by jamesknelson** [comment]
Probably could be updated, but I haven't run into this issue myself yet. Would happily merge a PR.
