### ISSUE TITLE
Is mdx.macro still maintainable?

### ISSUE THREAD

**Issue by smashboy** [frontarm/mdx-util#62]
Is this package (mdx.macro) even working? I was trying to add to my own project and also I was trying to run [example project](https://github.com/mdx-js/mdx/tree/master/examples/create-react-app) and in both examples I'm facing the same error: 
![image](https://user-images.githubusercontent.com/30213662/79130933-6dea2900-7db0-11ea-9212-42eea71e6d86.png)

**Comment by jamesknelson** [comment]
Not sure sorry, haven't looked at this project for a long time and don't really have time to do maintenance right now.

**Comment by smashboy** [comment]
@jamesknelson Thanks for answer. :+1:
