### ISSUE TITLE
mdxc as a runtime md parser?

### ISSUE THREAD

**Issue by gerhardsletten** [frontarm/mdx-util#7]
To clarify, can mdxc be used as a parser in runtime to convert markdown to react output?

The typical usecase would be that you have markdown stored in your database and wants to display it within an application.

**Comment by jamesknelson** [comment]
Only if you're the one putting the contents in the database. It should never be used for publicly submitted content.

**Comment by gerhardsletten** [comment]
Thanks

**Comment by miracle2k** [comment]
Looking at how the playground is implemented, it runs the generated JavaScript code through babel, and then through eval, which is not ideal for a production app. I don't think there is an API to actually generate a react component tree, is there?

**Comment by jamesknelson** [comment]
MDXC only knows how to generate ES6 text -- it can't directly generate React elements. That is why it is run through babel/eval.

My primary goal of MDXC is to provide a tool that can be used with Webpack to allow me to have markdown documents as components within a website. The playground is more of a hack to let people try it out.
