### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by jolic** [frontarm/mdx-util#8]
When I use the props example I get an error with webpack-dev-server:
```Uncaught SyntaxError: Unexpected token )```

The created React component looks like this:

```js
import React, { createElement, createFactory } from 'react'

export default function({ factories={}, value, onChange }) {
  const {
    wrapper = createFactory('div'),
    h1 = createFactory('h1'),
    p = createFactory('p'),
  } = factories

  return wrapper({},

h1({"id": "Hello!"},
  "Hello!",
),
p({},
  "May I kindly ask your name?",
),
createElement("input", {
  value: value,
  onChange: onChange
}),
createElement(
  "p",
  null,
  value && `Thanks, ${value}!`
)

  )
}

export const meta = {}
```

The error is here:
```
h1({"id": "Hello!"},
  "Hello!",
),    <----
```
The source:

```
prop value
prop onChange

# Hello!

May I kindly ask your name?

<input
  value={value}
  onChange={onChange}
/>

<p>{value && `Thanks, ${value}!`}</p>
```

And I get also the following error:

```warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.```

The mdx file is used in a rect component with 
```js
import TestMdx from './example.mdx';
...
render() {
...
   <TestMdx />
...
}
``` 

Any hints on this?

**Comment by jolic** [comment]
Webpack created code:

/***/ "./app/pages/live-editor/example.mdx":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_react__ = __webpack_require__(0);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_react___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_react__);\n\n\n/* harmony default export */ __webpack_exports__[\"a\"] = (function({ factories={}, value, onChange }) {\n  const {\n    wrapper = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0_react__[\"createFactory\"])('div'),\n    h1 = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0_react__[\"createFactory\"])('h1'),\n    p = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0_react__[\"createFactory\"])('p'),\n  } = factories\n\n  return wrapper({},\n\nh1({\"id\": \"Hello!\"},\n  \"Hello!\",\n),\np({},\n  \"May I kindly ask your name?\",\n),\n__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0_react__[\"createElement\"])(\"input\", {\n  value: value,\n  onChange: onChange\n}),\n__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0_react__[\"createElement\"])(\n  \"p\",\n  null,\n  value && `Thanks, ${value}!`\n)\n\n  )\n});\n\nconst meta = {}\n/* unused harmony export meta */\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9hcHAvcGFnZXMvbGl2ZS1lZGl0b3IvZXhhbXBsZS5tZHguanMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9hcHAvcGFnZXMvbGl2ZS1lZGl0b3IvZXhhbXBsZS5tZHg/Mjg0OCJdLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgUmVhY3QsIHsgY3JlYXRlRWxlbWVudCwgY3JlYXRlRmFjdG9yeSB9IGZyb20gJ3JlYWN0J1xuXG5leHBvcnQgZGVmYXVsdCBmdW5jdGlvbih7IGZhY3Rvcmllcz17fSwgdmFsdWUsIG9uQ2hhbmdlIH0pIHtcbiAgY29uc3Qge1xuICAgIHdyYXBwZXIgPSBjcmVhdGVGYWN0b3J5KCdkaXYnKSxcbiAgICBoMSA9IGNyZWF0ZUZhY3RvcnkoJ2gxJyksXG4gICAgcCA9IGNyZWF0ZUZhY3RvcnkoJ3AnKSxcbiAgfSA9IGZhY3Rvcmllc1xuXG4gIHJldHVybiB3cmFwcGVyKHt9LFxuXG5oMSh7XCJpZFwiOiBcIkhlbGxvIVwifSxcbiAgXCJIZWxsbyFcIixcbiksXG5wKHt9LFxuICBcIk1heSBJIGtpbmRseSBhc2sgeW91ciBuYW1lP1wiLFxuKSxcbmNyZWF0ZUVsZW1lbnQoXCJpbnB1dFwiLCB7XG4gIHZhbHVlOiB2YWx1ZSxcbiAgb25DaGFuZ2U6IG9uQ2hhbmdlXG59KSxcbmNyZWF0ZUVsZW1lbnQoXG4gIFwicFwiLFxuICBudWxsLFxuICB2YWx1ZSAmJiBgVGhhbmtzLCAke3ZhbHVlfSFgXG4pXG5cbiAgKVxufVxuXG5leHBvcnQgY29uc3QgbWV0YSA9IHt9XG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9hcHAvcGFnZXMvbGl2ZS1lZGl0b3IvZXhhbXBsZS5tZHhcbi8vIG1vZHVsZSBpZCA9IC4vYXBwL3BhZ2VzL2xpdmUtZWRpdG9yL2V4YW1wbGUubWR4XG4vLyBtb2R1bGUgY2h1bmtzID0gMCJdLCJtYXBwaW5ncyI6IkFBQUE7QUFBQTtBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOzsiLCJzb3VyY2VSb290IjoiIn0=");

**Comment by jamesknelson** [comment]
May I see your `webpack.config.js` and `.babelrc`?

**Comment by jolic** [comment]
I'm using [https://github.com/react-boilerplate/react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) and there is no ```.babelrc```.

They're using js files: [https://github.com/react-boilerplate/react-boilerplate/tree/master/internals/webpack](https://github.com/react-boilerplate/react-boilerplate/tree/master/internals/webpack)

I've added in ```webpack.base.babel.js```the following lines to the webpack config:

```
...
module: {
    loaders: [{
...
    }, {
      test: /\.mdx?$/,
      loaders: [
        'babel-loader',
        'mdx-loader',
      ],
    }],
  },
```
Now I get in the view:
![image](https://cloud.githubusercontent.com/assets/476477/25896164/4f024522-3583-11e7-8469-e55185d29946.png)

without the input field. And the error is:
![image](https://cloud.githubusercontent.com/assets/476477/25896189/6a57606e-3583-11e7-8331-be260b76b356.png)

**Comment by jolic** [comment]
React version is 15.5.4

**Comment by jamesknelson** [comment]
Looks like it works after you added babel. The generated MDX code doesn't use PropTypes or React.createClass so those warnings will be coming from somewhere else within your code base.

**Comment by jolic** [comment]
Yes, you're right. I've updated a couple of packages and the errors were gone.
Thank you. 👍
